[functions.priority-signup]
verify_jwt = false

[functions.newsletter-signup]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.restock-signup]
verify_jwt = false

[functions.admin-email]
verify_jwt = false

[functions.email-unsubscribe]
verify_jwt = false
